version: '3.9'

services:
  blog_database:
    image: postgres:16.1
    restart: always
    shm_size: 128mb
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    ports:
      - 5432:5432
    networks:
      - blog-local
      
  user_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - blog-local

volumes:
  database:
    driver: local

networks:
  blog-local:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16